---
- name: Spin Down Reverse Proxy
  hosts: reverseproxy
  tasks:
    - name: Docker Compose Down
      ansible.builtin.command:
        cmd: "docker compose down ./compose.yml"
        chdir: /opt/run/reverseproxy
