---
- name: Spin Up Reverse Proxy
  hosts: reverseproxy
  tasks:
    - name: Docker Compose Up
      ansible.builtin.command:
        cmd: "docker compose up ./compose.yml"
        chdir: /opt/run/reverseproxy
