---
alpine:
  hosts:
    pacci:
      ansible_host: 192.168.1.100
    mcgee:
      ansible_host: 192.168.1.101
    delilah:
      ansible_host: 192.168.1.102
    palmer:
      ansible_host: 192.168.1.103
    ziva:
      ansible_host: 192.168.1.104
    abby:
      ansible_host: 192.168.1.105
    ducky:
      ansible_host: 192.168.1.106
    kate:
      ansible_host: 192.168.1.107
    #vance
    #  ansible_host: 192.168.1.108
    jenny:
      ansible_host: 192.168.1.109
    bishop:
      ansible_host: 192.168.1.110
    majormassspec:
      ansible_host: 192.168.1.111
    tony:
      ansible_host: 192.168.1.112
  vars:
    ansible_python_interpreter: /usr/bin/python
tinkering:
  hosts:
    torres:
      ansible_host: 192.168.1.113
docker:
  hosts:
    jenny:
    mcgee:
    delilah:
    bishop:
    palmer:
    ziva:
    abby:
    majormassspec:
    ducky:
    pacci:
    kate:
    tony:
reverseproxy:
  hosts:
    jenny:
dns:
  hosts:
    mcgee:
chat:
  hosts:
    delilah:
mail:
  hosts:
    bishop:
fileserver:
  hosts:
    palmer:
website:
  hosts:
    ducky:
cloud:
  hosts:
    ziva:
git:
  hosts:
    abby:
taskrunners:
  hosts:
    majormassspec:
vpn:
  hosts:
    pacci:
photos:
  hosts:
    kate:
medialibrary:
  hosts:
    tony: